arch:
  arm64

os:
  linux

dist:
  focal

language:
  python

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

virtualenv:
  system-site-packages: true

addons:
  apt:
    packages:
      - git
      - python3-pip
      - python3-dev

install:
  - python3 -m pip install -r requirements.txt -r requirements_dev.txt
  - cd rpi-rgb-led-matrix/
  - make build-python PYTHON="$(command -v python3)"
  - sudo make install-python PYTHON="$(command -v python3)"
  - cd ../
  - cp config/config.json.example config/config.json

script:
  - python3 -m pytest -m "not slow"

branches:
  only:
    - master
    - dev
